# Generated by Django 4.1.4 on 2023-02-20 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eduction", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="age",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="courses",
        ),
        migrations.AlterField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="eduction.teacher",
            ),
        ),
    ]
