# Generated by Django 4.1.4 on 2023-02-22 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eduction", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("department", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=100)),
                ("phone", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="student",
            name="address",
        ),
        migrations.RemoveField(
            model_name="student",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="student",
            name="roll_no",
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=50)),
                ("credit", models.FloatField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eduction.teacher",
                    ),
                ),
            ],
        ),
    ]
